bug修复：游戏中特殊按键判定为ESC
mayerui/sudoku pull request #39
Opened 2024-04-25 16:12 UTC by sfiiae

linux下的getch中ESC返回27，而**上下左右**按键的返回需要读取三次，第一次的值为27与ESC冲突，会导致退出游戏提示，并且由于存在之前的输入会导致输入没法退出游戏

2024-05-28 08:39 UTC, mayerui requested changes

2024-05-28 08:39 UTC, mayerui commented on src/utility.inl
> +        // char c;
废弃的代码建议直接删除

2024-05-28 08:39 UTC, mayerui commented on src/utility.inl
> +    #include <fcntl.h>  /* 使用fcntl */
/* 使用fcntl */ 这个注释没有必要，建议删除

2024-05-28 08:39 UTC, mayerui commented on src/utility.inl
> +        return static_cast<char>(c);
修改后，输入ESC会返回27， 输入四个方向键均返回-1，对吗？

2024-06-02 01:57 UTC, sfiiae commented on src/utility.inl
> +        return static_cast<char>(c);
对的

2024-06-03 02:05 UTC, mayerui approved these changes

2024-06-03 02:06 UTC, merged